export const PAGE_TITLES = {
	landing: "Welcome",
	dashboard: "Dashboard",
	batch: "Batch Details",
	batchRecords: "Batch Records",
	patient: "Patient Details",
	patients: "Patients",
	product: "Product Details",
	products: "Products",
	reports: "Reports",
	stockMovement: "Stock Movement",
	stockRecords: "Stock Records",
	supplier: "Supplier Details",
	suppliers: "Suppliers",
	userManagement: "User Management",
	userProfile: "User Profile",
	approverDashboard: "Approver Dashboard",
	approverLayout: "Approver",
	login: "Login",
};
